### ISSUE TITLE
dont' work with QGIS 3.34

### ISSUE THREAD

**Issue by melanieparis** [oso/qgis-etri#9]
Hi, 

the plugin didn't work with QGIS 3.34 (he worked with 3.12).

I checked NULL Value and geom,  

![image](https://github.com/user-attachments/assets/b0f23174-9e33-41be-841d-d083a6540259)

Thanks

**Comment by oso** [comment]
Hello @melanieparis ,
I was able to reproduce the issue with the example layer under tests/data/loulouka.
I'll try to fix the issue this week. Thanks for the bug report.
Olivier

**Comment by oso** [comment]
I just made a fix. You can try with the latest version of the sources.

**Comment by melanieparis** [comment]
Thanks a lot, it works ! we use this plugin very often for wetlands of Bourgogne-Franche-Comté !

**Comment by oso** [comment]
Happy to know that my master thesis project is still used 13 years after I graduated :-)
